In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [11]:
import pandas as pd

train_df = pd.read_csv('fraudTrain.csv')
test_df = pd.read_csv('fraudTest.csv')

In [12]:
train_df = train_df.drop(['first', 'last' , 'street'],axis=1)
test_df = test_df.drop(['first', 'last' , 'street'],axis=1)

In [13]:
label_encoders = {}

In [14]:
categorical_columns = ['merchant','category','gender']

In [17]:
for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    train_df[column] = label_encoders[column].fit_transform(train_df[column])
    test_df[column] = label_encoders[column].transform(test_df[column])

In [19]:

import pandas as pd
train_df['trans_date_trans_time'] = pd.to_datetime(train_df['trans_date_trans_time'])
test_df['trans_date_trans_time'] = pd.to_datetime(test_df['trans_date_trans_time'])


In [20]:
for df in [train_df,test_df]:
    df['transaction_year'] = df['trans_date_trans_time'].dt.year
    df['transaction_month'] = df['trans_date_trans_time'].dt.month
    df['transaction_day'] = df['trans_date_trans_time'].dt.day
    df['transaction_hour'] = df['trans_date_trans_time'].dt.hour
    df.drop('trans_date_trans_time',axis=1,inplace=True)




In [22]:
X_train = train_df.drop(['cc_num','is_fraud'],axis=1)
y_train = train_df['is_fraud']
X_test = test_df.drop(['cc_num','is_fraud'],axis=1)
y_test = test_df['is_fraud']


In [23]:
X_train = X_train.apply(pd.to_numeric , errors='coerce')
X_test = X_test.apply(pd.to_numeric , errors='coerce')


In [24]:
X_train.fillna(0,inplace=True)
X_test.fillna(0,inplace=True)


In [25]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
rf_model = RandomForestClassifier(n_estimators=100,random_state = 42)
rf_model.fit(X_train_scaled,y_train)

RandomForestClassifier(random_state=42)

In [28]:
lr_model = LogisticRegression(max_iter=1000,random_state=42)
lr_model.fit(X_train_scaled,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [29]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [30]:
def evaluate_model(model,X_test,y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    cm = confusion_matrix(y_test,y_pred)
    report = classification_report(y_test,y_pred)
    return accuracy,cm ,report

In [31]:
rf_accuracy , rf_cm ,rf_report = evaluate_model(rf_model,X_test_scaled , y_test)

lr_accuracy , lr_cm ,lr_report = evaluate_model(lr_model,X_test_scaled , y_test)

dt_accuracy , dt_cm ,dt_report = evaluate_model(dt_model,X_test_scaled , y_test)



In [33]:
print("Random Forest Classifier:")
print(f"Accuracy:{rf_accuracy}")
print("confusion matrix:")
print(rf_cm)
print("classification_report:")
print(rf_report)

Random Forest Classifier:
Accuracy:0.9982869039928453
confusion matrix:
[[553463    111]
 [   841   1304]]
classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.92      0.61      0.73      2145

    accuracy                           1.00    555719
   macro avg       0.96      0.80      0.87    555719
weighted avg       1.00      1.00      1.00    555719



In [34]:
print("\logistic regression:")
print(f"Accuracy:{lr_accuracy}")
print("confusion matrix:")
print(lr_cm)
print("classification_report:")
print(lr_report)

\logistic regression:
Accuracy:0.9959529906301566
confusion matrix:
[[553470    104]
 [  2145      0]]
classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.00      0.00      0.00      2145

    accuracy                           1.00    555719
   macro avg       0.50      0.50      0.50    555719
weighted avg       0.99      1.00      0.99    555719



In [35]:
print("\ndecison tree Classifier:")
print(f"Accuracy:{dt_accuracy}")
print("confusion matrix:")
print(dt_cm)
print("classification_report:")
print(dt_report)


decison tree Classifier:
Accuracy:0.9938800005038517
confusion matrix:
[[551188   2386]
 [  1015   1130]]
classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.32      0.53      0.40      2145

    accuracy                           0.99    555719
   macro avg       0.66      0.76      0.70    555719
weighted avg       1.00      0.99      0.99    555719

